<?php
	
	include("../../files/config.php");
	include("DbConnection.php");
	include_once("Classes/PHPExcel.php");
	$dbconnect -> connect($DBuser, $DBpass, $DBurl );
	$dbconnect -> useDb($Database);		
	$sheet = new PHPExcel();
	$activeSheet = $sheet->getActiveSheet();
	session_start();
	
	//Formatting
	$cellformat = array();
	$activeSheet->mergeCells('A1:L2');
	$activeSheet->mergeCells('A3:F3');
	$activeSheet->mergeCells('H3:L3');
	$activeSheet->mergeCells('N3:R3');
	$header1 = array(
		'font'  => array(
			'bold'  => true,
			'size'  => 15,
		),
		'fill' => array(
			'type'=> PHPEXCEL_Style_Fill::FILL_SOLID,
			'color'=> array('rgb'=>'A0A0A0'),
		),
		'alignment' => array(
            'horizontal' => PHPExcel_Style_Alignment::HORIZONTAL_CENTER,
			'vertical'=>PHPExcel_Style_Alignment::VERTICAL_CENTER,
		),
		'borders' => array(
          'allborders' => array(
              'style' => PHPExcel_Style_Border::BORDER_THIN
			)
		 )
		
	);
	
	$header2 = array(
    'font'  => array(
        'bold'  => true,
        'size'  => 13,
    ),
		'fill' => array(
			'type'=> PHPEXCEL_Style_Fill::FILL_SOLID,
			'color'=> array('rgb'=>'A0A0A0'),
		),
		'alignment' => array(
            'horizontal' => PHPExcel_Style_Alignment::HORIZONTAL_CENTER,
			'vertical'=>PHPExcel_Style_Alignment::VERTICAL_CENTER,
		)
	);
	
	$header3 = array(
    'font'  => array(
        'bold'  => true,
        'size'  => 11,
    ),
		'alignment' => array(
            'horizontal' => PHPExcel_Style_Alignment::HORIZONTAL_CENTER,
			'vertical'=>PHPExcel_Style_Alignment::VERTICAL_CENTER,
		));
	
	
	
    $activeSheet->getStyle("A1:L2")->applyFromArray($header1);
	$activeSheet->getStyle("A3:F3")->applyFromArray($header2);
	$activeSheet->getStyle("H3:L3")->applyFromArray($header2);
	$activeSheet->getStyle("N3:R3")->applyFromArray($header2);
	$activeSheet->getStyle("A4:F4")->applyFromArray($header3);
	$activeSheet->getStyle("H4:L4")->applyFromArray($header3);
	$activeSheet->getStyle("N4:R4")->applyFromArray($header3);
	$activeSheet->getRowDimension(3)->setRowHeight(32);
	$activeSheet->getRowDimension(4)->setRowHeight(32);		
	foreach(range('A','R') as $columnID) {
    $activeSheet->getColumnDimension($columnID)->setAutoSize(true);
	}	
	//Headers fixed	
	$activeSheet -> setCellValue('A1','Stock Inventory As of '.date('F Y'));
	$activeSheet -> setCellValue('A3','Inventory Warehouse');
	$activeSheet -> setCellValue('H3','Issuances');
	$activeSheet -> setCellValue('N3','Purchases');
	$activeSheet -> setCellValue('M1','Generated By: ');
	$activeSheet -> setCellValue('M2','Generated On: ');
	$activeSheet -> setCellValue('N1',$_SESSION["EmpName"]);
	$activeSheet -> setCellValue('N2',''.date('F d Y',time()));
	//Inventory Header
	$activeSheet -> setCellValue('A4','Item Name');
	$activeSheet -> setCellValue('B4','Item Code');
	$activeSheet -> setCellValue('C4','Quantity');
	$activeSheet -> setCellValue('D4','Amount per Unit');
	$activeSheet -> setCellValue('E4','Amount');
	$activeSheet -> setCellValue('F4','Description');
	//Issuance Header
	$activeSheet -> setCellValue('H4','Item Name');
	$activeSheet -> setCellValue('I4','Date of Issuance');
	$activeSheet -> setCellValue('J4','Previous Quantity');
	$activeSheet -> setCellValue('K4','Qty Issued');
	$activeSheet -> setCellValue('L4','Issuance No.');
	//Purchases Header
	$activeSheet -> setCellValue('N4','Item Name');
	$activeSheet -> setCellValue('O4','Date of Deposit');
	$activeSheet -> setCellValue('P4','Previous Quantity');
	$activeSheet -> setCellValue('Q4','Qty Deposited');
	$activeSheet -> setCellValue('R4','Purchase No.');
	//////////////////
	
	//////////////////////////////////
	//Queries
	//////////////////////////////////
	$cell=5;
	$query = mysql_query('Select * From item_table where status="active"');
	$cellformat[] = mysql_num_rows($query);
	while($results = mysql_fetch_array($query)){
			$amount = $results['unit_price']*$results['quantity'];	
			$activeSheet -> setCellValue('A'.$cell,$results['item_name']);
			$activeSheet -> setCellValue('B'.$cell,$results['item_code']);
			$activeSheet -> setCellValue('C'.$cell,$results['quantity']);
			$activeSheet -> setCellValue('D'.$cell,$results['unit_price']);
			$activeSheet -> setCellValue('E'.$cell,$amount);
			$activeSheet -> setCellValue('F'.$cell,$results['description']);
			$cell = $cell+1;
			$totalAmount = $totalAmount +$amount;
	}
	$activeSheet -> setCellValue('E'.$cell,$totalAmount);
	$activeSheet -> setCellValue('D'.$cell,"TOTAL AMOUNT:" );
	$cell = 5;
	
	$query = mysql_query('Select * From item_logs_table WHERE issuance_no IS NOT NULL');
	$cellformat[] = mysql_num_rows($query);
	while($results = mysql_fetch_array($query)){
			$activeSheet -> setCellValue('H'.$cell,$results['Item_Name']);
			$activeSheet -> setCellValue('I'.$cell,$results['Timestamp']);
			$activeSheet -> setCellValue('J'.$cell,$results['Previous']);
			$activeSheet -> setCellValue('K'.$cell,$results['Quantity']);
			$activeSheet -> setCellValue('L'.$cell,$results['issuance_no']);
			$cell = $cell+1;
	}
	$cell = 5;
	$query = mysql_query('Select * From item_logs_table WHERE purchase_order IS NOT NULL');
	$cellformat[] = mysql_num_rows($query);
	while($results = mysql_fetch_array($query)){
			$activeSheet -> setCellValue('N'.$cell,$results['Item_Name']);
			$activeSheet -> setCellValue('O'.$cell,$results['Timestamp']);
			$activeSheet -> setCellValue('P'.$cell,$results['Previous']);
			$activeSheet -> setCellValue('Q'.$cell,$results['Quantity']);
			$activeSheet -> setCellValue('R'.$cell,$results['purchase_order']);
			$cell = $cell+1;
	}
	$formatby = max($cellformat)+1;
	for($i=1;$i<=$formatby; $i++){
		$activeSheet->getRowDimension($i+4)->setRowHeight(25);	
	}
	
	
	$activeSheet -> setCellValue('A40',$formatby);
	$activeSheet -> setCellValue('B40',asda );
	
	
	
	
	$objWriter = PHPExcel_IOFactory::createWriter($sheet, 'Excel2007');
	header('Content-Type: application/vnd.ms-excel');
	header('Content-Disposition: attachment;filename="inventory.xlsx"');
	header('Cache-Control: max-age=0');
	ob_end_clean();
	$objWriter->save('php://output');
	
?>